/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import busmanagement.AccountManagement;
import busmanagement.BusManagement;
import busmanagement.EmployeeManagement;
import busmanagement.Login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TranKhang
 */
public class PhanCong extends javax.swing.JFrame {

    /**
     * Creates new form QLChuyen
     * 
     * 
     */
    public static String infor;
    
       public void setInfor(String infor)
    {
        this.infor = infor;
        this.inforText.setText(infor);
    }
    
    
    public PhanCong() {
        initComponents();
        jButton4.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        inforText = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btChosse = new javax.swing.JButton();
        cbbTX = new javax.swing.JComboBox<>();
        cbbTime = new javax.swing.JComboBox<>();
        cbbPX = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtDel = new javax.swing.JButton();
        cbbYear = new javax.swing.JComboBox<>();
        jbtAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbDay = new javax.swing.JComboBox<>();
        cbbBus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(256, 720));

        jButton1.setText("Quản lý nhân viên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quản lý xe bus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quản lý tài khoản");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Quản lý tuyến xe");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Thống kê");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Đăng xuất");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        inforText.setEditable(false);
        inforText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inforText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inforText.setText("this is some random text");
        inforText.setAutoscrolls(false);
        inforText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inforText.setEnabled(false);
        jScrollPane3.setViewportView(inforText);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin người dùng");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton4.setText("Phân công");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Quản lý chuyến xe");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Quản lý vé");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jButton9.getAccessibleContext().setAccessibleDescription("");

        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Vé", "Loại vé", "Giá tiền"
            }
        ));
        tableMain.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableMainAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMainMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMain);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Phân Công");

        btChosse.setText("Chọn");
        btChosse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChosseActionPerformed(evt);
            }
        });

        cbbTX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTXActionPerformed(evt);
            }
        });

        cbbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbPX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Phụ xe:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tháng:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bus:");

        cbbM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cbbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tài xế:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Năm:");

        jbtDel.setText("Xóa");
        jbtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDelActionPerformed(evt);
            }
        });

        cbbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", " " }));
        cbbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbYearActionPerformed(evt);
            }
        });

        jbtAdd.setText("Phân công");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ngày:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Chuyến số:");

        cbbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbBus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbTX, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbPX, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(cbbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbbM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cbbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(64, 64, 64)
                                                        .addComponent(btChosse, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jbtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(289, 289, 289))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(439, 439, 439))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btChosse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbPX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbBus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Date date= new Date();
    java.sql.Date sqlDate = new java.sql.Date(date.getTime());
    
    
    private void showData(){
        try{
            //tableMain.removeAll();
            String[] arr = {"Bus ID","Biển số","ID nhân viên"," Họ tên","Vị trí","Time ID","Bắt đầu","Kết thúc","Đến ngày"};
            DefaultTableModel model=  new DefaultTableModel(arr,0);
            
            Connection connection = DBConnection.getConnection();
            String query= "SELECT * FROM view_info_work order by  work_day desc , bus_id" ;
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs= ps.executeQuery();
            while(rs.next()){
                Vector vt= new Vector();
                vt.add(rs.getString("bus_id"));
                vt.add(rs.getString("license_plate"));
                vt.add(rs.getString("emp_id"));      
                vt.add(rs.getString("hoten"));
                vt.add(rs.getString("position"));
                vt.add(rs.getString("time_id"));
                vt.add(rs.getString("start_time"));
                vt.add(rs.getString("end_time"));
                vt.add(rs.getString("work_day"));
               
                model.addRow(vt);
    
        }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);  
        }catch(SQLException ex){
            Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
//    private void showBusEMP(){
//        try{
//            //tableMain.removeAll();
//            String[] arr = {"Bus ID","ID nhân viên"};
//            DefaultTableModel model=  new DefaultTableModel(arr,0);
//            
//            Connection connection = DBConnection.getConnection();
//            String query= "SELECT * FROM dbo.Bus_EMP " ;
//            PreparedStatement ps = connection.prepareStatement(query);
//            ResultSet rs= ps.executeQuery();
//            while(rs.next()){
//                Vector vt= new Vector();
//                vt.add(rs.getString("bus_id"));
//                vt.add(rs.getString("emp_id"));
// 
//                model.addRow(vt);
//    
//        }
//            DBConnection.closeConnection(connection);
//            jtbBusEMP.setModel(model);  
//        }catch(SQLException ex){
//            Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    
    public class ComboItem {

    private Object value;
    private Object label;

    public ComboItem(Object value, Object label) {
        this.value = value;
        this.label = label;
    }

    public int getID() {
        return Integer.parseInt(value.toString());
    }

    public String getLabel() {
        return this.label.toString();
    }

    @Override
    public String toString() {
        return label.toString();
    }
}
    
    private void fillComboboxDay(){
        
        
        String m= cbbM.getSelectedItem().toString();
        String year= cbbYear.getSelectedItem().toString();
     
     try{      
        Connection connection = DBConnection.getConnection();
        String query= "EXEC sp_getDay @month= '"+m+"' ,"+"@Year= '"+year+"' ";
        PreparedStatement ps = connection.prepareCall(query);
//        PreparedStatement ps = connection.prepareStatement(query);
//        ps.setString(1, cbbM.getSelectedItem().toString());
//        ps.setString(2, cbbYear.getSelectedItem().toString());
        ps.executeQuery();
        ResultSet rs= ps.executeQuery();
        
        DefaultComboBoxModel cbb= (DefaultComboBoxModel) cbbDay.getModel();
        cbb.removeAllElements();

        while(rs.next()){

            String days= rs.getString("day");
            
            cbb.addElement(days);
            
        }
        
    }catch(SQLException ex){
        Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void fillComboboxbus(){
        
        
        String day= cbbDay.getSelectedItem().toString();
        String m= cbbM.getSelectedItem().toString();
        int year= Integer.parseInt(cbbYear.getSelectedItem().toString());
     
     try{      
        Connection connection = DBConnection.getConnection();
        String query= "EXEC sp_WorkBus @day= '"+ day+ "', @m= '"+m+"', @year= '"+year+"' ";
        PreparedStatement ps = connection.prepareCall(query);
//        ps.setString(1, cbbDay.getSelectedItem().toString());
//        ps.setString(2, cbbYear.getSelectedItem().toString());
        ps.executeQuery();
        ResultSet rs= ps.executeQuery();
        
        DefaultComboBoxModel cbb= (DefaultComboBoxModel) cbbBus.getModel();
        cbb.removeAllElements();
        

        while(rs.next()){
            int idbus= rs.getInt("bus_id");
            String number= rs.getString("route_id");
            
            ComboItem mycbb= new ComboItem(idbus, number);
            
            cbb.addElement(mycbb);
            
        }
        
    }catch(SQLException ex){
        Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void fillComboboxTX(){
        
    
     try{      
        Connection connection = DBConnection.getConnection();
        String query= "{call sp_WorkEMP1(?,?,?)}";
        PreparedStatement ps = connection.prepareStatement(query);
        ps.setString(1, cbbDay.getSelectedItem().toString());
        ps.setString(2, cbbM.getSelectedItem().toString());
        ps.setString(3, cbbYear.getSelectedItem().toString());
        ps.executeQuery();
        ResultSet rs= ps.executeQuery();
        
        DefaultComboBoxModel cbb= (DefaultComboBoxModel) cbbTX.getModel();
        cbb.removeAllElements();
        
        while(rs.next()){
            int idbus= rs.getInt("emp_id");
            String name= rs.getString("fullname");
            //String position= rs.getString("position");
     
            ComboItem mycbb= new ComboItem(idbus, name);
            
            cbb.addElement(mycbb);
            
        }
        
    }catch(SQLException ex){
        Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void fillComboboxPX(){
        
    
     try{      
        Connection connection = DBConnection.getConnection();
        String query= "{call sp_WorkEMP2(?,?,?)}";
        PreparedStatement ps = connection.prepareStatement(query);
        ps.setString(1, cbbDay.getSelectedItem().toString());
        ps.setString(2, cbbM.getSelectedItem().toString());
        ps.setString(3, cbbYear.getSelectedItem().toString());
        ps.executeQuery();
        ResultSet rs= ps.executeQuery();
        
        DefaultComboBoxModel cbb= (DefaultComboBoxModel) cbbPX.getModel();
        cbb.removeAllElements();
        
        while(rs.next()){
            int idbus= rs.getInt("emp_id");
            String name= rs.getString("fullname");
            //String position= rs.getString("position");
     
            ComboItem mycbb= new ComboItem(idbus, name);
            
            cbb.addElement(mycbb);
            
        }
        
    }catch(SQLException ex){
        Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void fillComboboxTIME(){
        
    
     try{      
        Connection connection = DBConnection.getConnection();
        String query= "SELECT * FROM TIME";
        PreparedStatement ps = connection.prepareStatement(query);
        ResultSet rs= ps.executeQuery();
        
        DefaultComboBoxModel cbb= (DefaultComboBoxModel) cbbTime.getModel();
        cbb.removeAllElements();
        
        while(rs.next()){
            String idbus= rs.getString("time_id");
            //MyCombobox mycbb= new MyCombobox(idbus);
            cbb.addElement(idbus);
        }
        
    }catch(SQLException ex){
        Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private boolean checkBusEMP1(){
    
        ComboItem nb= (ComboItem) cbbBus.getSelectedItem();
        int busID = nb.getID();

        ComboItem tx= (ComboItem) cbbTX.getSelectedItem();
        int txID = tx.getID();

  
        
        try{
            Connection connection = DBConnection.getConnection();
            String query= "SELECT * FROM dbo.BUS_EMP WHERE bus_id ="+ busID+"AND emp_id=" + txID;
            PreparedStatement ps = connection.prepareStatement(query);
            //ps.setString(1, busID);
            //ps.setString(2, txID);
            ResultSet rs= ps.executeQuery();
            while(rs.next()){
                return true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
     private boolean checkBusEMP2(){
    
        ComboItem nb= (ComboItem) cbbBus.getSelectedItem();
        int busID = nb.getID();

        ComboItem px= (ComboItem) cbbPX.getSelectedItem();
        int pxID = px.getID();
         
        try{
            Connection connection = DBConnection.getConnection();
            String query= "SELECT * FROM dbo.BUS_EMP WHERE bus_id ="+ busID+"AND emp_id="+pxID;
            PreparedStatement ps = connection.prepareStatement(query);
//            ps.setString(1, busID);
//            ps.setString(2, pxID);
            ResultSet rs= ps.executeQuery();
            while(rs.next()){
                return true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    
    
    private void tableMainAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableMainAncestorAdded
        showData();
        //showBusEMP();
        fillComboboxbus();
        fillComboboxTIME();
        fillComboboxPX();
        fillComboboxTX();
        fillComboboxDay();
        //showBusEMP();
        jbtAdd.setEnabled(false);
        jbtDel.setEnabled(false);
        
        
    }//GEN-LAST:event_tableMainAncestorAdded

    
    private void tableMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMainMouseClicked
        
        int pos= tableMain.getSelectedRow();
        cbbBus.setSelectedItem(tableMain.getModel().getValueAt(pos, 0).toString());
        cbbTX.setSelectedItem(tableMain.getModel().getValueAt(pos, 2).toString());
        cbbTime.setSelectedItem(tableMain.getModel().getValueAt(pos, 5).toString());
        
       
        jbtDel.setEnabled(true);
    }//GEN-LAST:event_tableMainMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
    }//GEN-LAST:event_formMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
                    QLTime qlc= new QLTime();
       
        qlc.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               qlc.setInfor(this.infor);
                    qlc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            QLChuyen qlc= new QLChuyen();
         qlc.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               qlc.setInfor(this.infor);
                    qlc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        QLVe qlc= new QLVe();
          qlc.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               qlc.setInfor(this.infor);
                    qlc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Thongke qlc= new Thongke();
         qlc.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               qlc.setInfor(this.infor);
                    qlc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
           Login log = new Login();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
                //System.out.println(this.infor);
               
              // System.out.println(bus.infor);
               this.dispose();  
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmployeeManagement emp = new EmployeeManagement();
                
                emp.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               emp.setInfor(this.infor);
               emp.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AccountManagement acc = new AccountManagement();
                acc.setVisible(true);
                acc.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               acc.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BusManagement bus = new BusManagement();
                bus.setVisible(true);
                bus.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               bus.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btChosseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChosseActionPerformed

        fillComboboxbus();
        fillComboboxTX();
        fillComboboxPX();
        
        jbtAdd.setEnabled(true);
        

    }//GEN-LAST:event_btChosseActionPerformed

    private void cbbTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTXActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed

        ComboItem nb= (ComboItem) cbbBus.getSelectedItem();
        int busID = nb.getID();

        ComboItem tx= (ComboItem) cbbTX.getSelectedItem();
        int txID = tx.getID();

        ComboItem px= (ComboItem) cbbPX.getSelectedItem();
        int pxID = px.getID();

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(cbbDay.getSelectedItem().toString()) );
        cal.set(Calendar.MONTH, Integer.parseInt(cbbM.getSelectedItem().toString()) -1 );
        cal.set(Calendar.YEAR, Integer.parseInt(cbbYear.getSelectedItem().toString()));
        date= cal.getTime();
        
       
        
        

        if(checkBusEMP2()==true ){
            try{
                Connection connection = DBConnection.getConnection();
                String query= "INSERT INTO dbo.WORK( bus_id, emp_id, time_id, work_day)"
                + "VALUES(?,?,?,?)";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setInt(1,busID);
                ps.setInt(2,pxID);
                ps.setString(3,cbbTime.getSelectedItem().toString());
                ps.setDate(4, new java.sql.Date(date.getTime()));

                ps.execute();

                showData();
                //showBusEMP();
                DBConnection.closeConnection(connection);

                JOptionPane.showMessageDialog(null, "Phân công phụ xe thành công.");

            }catch (SQLException ex) {
                Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{

            try{

                Connection connection = DBConnection.getConnection();
                String query= "INSERT INTO dbo.WORK( bus_id, emp_id, time_id, work_day)"
                + "VALUES(?,?,?,?)";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setInt(1,busID);
                ps.setInt(2,pxID);
                ps.setString(3,cbbTime.getSelectedItem().toString());
                ps.setDate(4, new java.sql.Date(date.getTime()));

                ps.execute();

                String query1= "INSERT INTO dbo.BUS_EMP( bus_id, emp_id)"
                + "VALUES(?,?)";
                PreparedStatement ps1 = connection.prepareStatement(query1);
                ps1.setInt(1,busID);
                ps1.setInt(2,pxID);

                ps1.execute();

                showData();
                //showBusEMP();
                DBConnection.closeConnection(connection);

                JOptionPane.showMessageDialog(null, "Phân công phụ xe thành công.");

            }catch (SQLException ex) {
                Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if(checkBusEMP1()==true ){

            try{

                Connection connection = DBConnection.getConnection();
                String query3= "INSERT INTO dbo.WORK( bus_id, emp_id, time_id, work_day)"
                + "VALUES(?,?,?,?)";
                PreparedStatement ps3 = connection.prepareStatement(query3);
                ps3.setInt(1,busID);
                ps3.setInt(2,txID);
                ps3.setString(3,cbbTime.getSelectedItem().toString());
                ps3.setDate(4, new java.sql.Date(date.getTime()));

                ps3.execute();

                showData();
                //showBusEMP();
                DBConnection.closeConnection(connection);

                JOptionPane.showMessageDialog(null, "Phân công tài xế thành công.");

            } catch (SQLException ex) {
                Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{

            try{

                Connection connection = DBConnection.getConnection();
                String query3= "INSERT INTO dbo.WORK( bus_id, emp_id, time_id, work_day)"
                + "VALUES(?,?,?,?)";
                PreparedStatement ps3 = connection.prepareStatement(query3);
                ps3.setInt(1,busID);
                ps3.setInt(2,txID);
                ps3.setString(3,cbbTime.getSelectedItem().toString());
                ps3.setDate(4, new java.sql.Date(date.getTime()));

                ps3.execute();

                String query4= "INSERT INTO dbo.BUS_EMP( bus_id, emp_id)"
                + "VALUES(?,?)";
                PreparedStatement ps4 = connection.prepareStatement(query4);
                ps4.setInt(1,busID);
                ps4.setInt(2,txID);

                ps4.execute();

                showData();
                //showBusEMP();
                DBConnection.closeConnection(connection);

                JOptionPane.showMessageDialog(null, "Phân công tài xế thành công.");

            }catch (SQLException ex) {
                Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        fillComboboxbus();
        fillComboboxTX();
        fillComboboxPX();
        
        jbtAdd.setEnabled(true);
        

    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelActionPerformed

        int result= JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa?");
        if (result==0){

            int pos= tableMain.getSelectedRow();
            String bus= tableMain.getModel().getValueAt(pos, 0).toString();
            String emp= tableMain.getModel().getValueAt(pos, 2).toString();
            String time= tableMain.getModel().getValueAt(pos, 5).toString();
            String day= tableMain.getModel().getValueAt(pos, 8).toString();

            try{
                Connection connection = DBConnection.getConnection();
                String query= "DELETE FROM dbo.WORK WHERE bus_id= ? AND time_id=? AND work_day=?";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, bus);
                //ps.setString(2, emp);
                ps.setString(2, time);
                ps.setString(3, day);

                ps.executeUpdate();

                showData();
                //showBusEMP();
                DBConnection.closeConnection(connection);

                JOptionPane.showMessageDialog(null, "Xóa thành công.");
            } catch (SQLException ex) {
                Logger.getLogger(QLChuyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        fillComboboxbus();
        fillComboboxTX();
        fillComboboxPX();
    }//GEN-LAST:event_jbtDelActionPerformed

    private void cbbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbYearActionPerformed

        // fillComboboxDay();
    }//GEN-LAST:event_cbbYearActionPerformed

    private void cbbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMActionPerformed

    }//GEN-LAST:event_cbbMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhanCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChosse;
    private javax.swing.JComboBox<String> cbbBus;
    private javax.swing.JComboBox<String> cbbDay;
    private javax.swing.JComboBox<String> cbbM;
    private javax.swing.JComboBox<String> cbbPX;
    private javax.swing.JComboBox<String> cbbTX;
    private javax.swing.JComboBox<String> cbbTime;
    private javax.swing.JComboBox<String> cbbYear;
    private javax.swing.JTextPane inforText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtDel;
    private javax.swing.JTable tableMain;
    // End of variables declaration//GEN-END:variables
}
