/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busmanagement;

import busmanagement.Account.Account;
import static busmanagement.AccountManagement.establishCon;
import busmanagement.Bus.Bus;
import busmanagement.employee.Employee;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import views.PhanCong;
import views.QLChuyen;
import views.QLTime;
import views.QLVe;
import views.Thongke;
/**
 *
 * @author Admin
 */
public class BusManagement extends javax.swing.JFrame {

    /**
     * Creates new form BusManagement
     */
    public static String infor;
    public void setInfor(String infor)
    {
        this.infor = infor;
        this.inforText.setText(infor);
    }
            
    public BusManagement() {
        initComponents();
        displayBusList();
        
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
    }
    
          public ArrayList<Bus> getBusList(){
        ArrayList<Bus> buses = new ArrayList<>();
        Connection con = establishCon();
        Statement st =null;
        try {
            
            String busQueryAll = "SELECT * FROM BUS";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(busQueryAll);
            while(rs.next())
            {
                Bus bus = new Bus(rs.getInt("bus_id"), rs.getInt("route_id"), rs.getInt("status"), rs.getString("license_plate"), rs.getString("bus_type"), rs.getDate("start_use"));
                buses.add(bus);
               
            }
            
        }
         catch (Exception e){
             e.printStackTrace();
         }
        finally{
            if(st !=null)
               {
                   try{
                       st.close();
                   }
                   catch (Exception e)
                   {
                       e.printStackTrace();
                   }
               }
               
              if(con !=null)
               {
                   try{
                       con.close();
                   }
                   catch (Exception e)
                   {
                       e.printStackTrace();
                   }
               }
        }
        return buses;
    
    }
          public void displayBusList()
    {
        ArrayList<Bus> buses = getBusList();
        DefaultTableModel model = (DefaultTableModel)busTable.getModel();
       
        Object [] rows = new Object[10];
        for(int i=0; i<buses.size(); i++)
        {
            
            rows[0] = buses.get(i).getBusId();
            rows[1] = buses.get(i).getRouteId();
          
            rows[2] = buses.get(i).getLicensePlate();
            rows[3] = buses.get(i).getBusType();
            rows[4] = buses.get(i).getStartUse();
            rows[5] = buses.get(i).getStatus();
            
            model.addRow(rows);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inforPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inforText = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        empmButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        routeIdText = new javax.swing.JTextField();
        licensePlateText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        busTable = new javax.swing.JTable();
        busTypeCombo = new javax.swing.JComboBox<>();
        statusCombo = new javax.swing.JComboBox<>();
        swMonthCombo = new javax.swing.JComboBox<>();
        swYearText = new javax.swing.JTextField();
        swDayText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(256, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin người dùng");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        inforText.setEditable(false);
        inforText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inforText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inforText.setText("this is some random text");
        inforText.setAutoscrolls(false);
        inforText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inforText.setEnabled(false);
        jScrollPane2.setViewportView(inforText);

        jButton6.setText("Phân công");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setText("Quản lý chuyến xe");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Thống kê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setText("Đăng xuất");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setText("Quản lý tài khoản");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Quản lý vé");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        empmButton.setText("Quản lý nhân viên");
        empmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empmButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Quản lý xe bus");

        jButton3.setText("Quản lý tuyến xe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inforPanelLayout = new javax.swing.GroupLayout(inforPanel);
        inforPanel.setLayout(inforPanelLayout);
        inforPanelLayout.setHorizontalGroup(
            inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        inforPanelLayout.setVerticalGroup(
            inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(empmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inforPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inforPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(983, 720));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã tuyến:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Biển số xe:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Loại xe:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ngày hoạt động:");

        routeIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeIdTextActionPerformed(evt);
            }
        });

        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Sửa");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Trạng thái:");

        ResetButton.setText("Đặt lại");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        busTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Mã tuyến", "Biển số xe", "Loại xe", "Ngày hoạt động", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        busTable.getTableHeader().setReorderingAllowed(false);
        busTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(busTable);

        busTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại xe--", "Xe 20 chỗ", "Xe 30 chỗ", "Xe 40 chỗ" }));
        busTypeCombo.setFocusable(false);

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Không Hoạt động", "Đang sửa chữa" }));
        statusCombo.setFocusable(false);

        swMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn tháng", "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(45, 50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResetButton)
                            .addComponent(licensePlateText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(routeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(165, 165, 165)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                        .addGap(194, 194, 194))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(busTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(182, 182, 182)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(swDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(swMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(swYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(7, 7, 7)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlateText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          AccountManagement acc = new AccountManagement();
                acc.setVisible(true);
                acc.setLocationRelativeTo(null);
                //System.out.println(this.infor);
               acc.setInfor(this.infor);
              // System.out.println(bus.infor);
               this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void empmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empmButtonActionPerformed
        // TODO add your handling code here:
          EmployeeManagement emp = new EmployeeManagement();
                emp.setVisible(true);
                emp.setLocationRelativeTo(null);
                //System.out.println(this.infor);
               emp.setInfor(this.infor);
              // System.out.println(bus.infor);
               this.dispose();
        
    }//GEN-LAST:event_empmButtonActionPerformed

    private void routeIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeIdTextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String routeId, busType, status, licensePlate, swDay, swYear;
        int swMonth;
        LocalDate swDate;
        routeId = routeIdText.getText();
        busType = busTypeCombo.getSelectedItem().toString();
        status = statusCombo.getSelectedItem().toString();
        licensePlate = licensePlateText.getText();
        swDay = swDayText.getText();
        
        swYear = swYearText.getText();
        if(status.equals("Hoạt động")){
            status = "1";
        }
        else if(status.equals("Không Hoạt động"))
        {
            status = "0";
        }
        else{
            status = "5";
        }
        switch (swMonthCombo.getSelectedItem().toString())
       {
            case "Tháng 1":
                swMonth = 1;
                break;
            case "Tháng 2":
                swMonth = 2;
                break;
            case "Tháng 3":
                swMonth = 3;
                break;
            case "Tháng 4":
                swMonth = 4;
                break;
            case "Tháng 5":
                swMonth = 5;
                break;
            case "Tháng 6":
                swMonth = 6;
                break;
            case "Tháng 7":
                swMonth = 7;
                break;
            case "Tháng 8":
                swMonth = 8;
                break;
            case "Tháng 9":
                swMonth = 9;
                break;
            case "Tháng 10":
                swMonth = 10;
                break;
            case "Tháng 11":
                swMonth = 11;
                break;
            case "Tháng 12":
                swMonth = 12;
                break;
            default: 
                swMonth = 0;
                       
        }
        swDate = LocalDate.of(Integer.parseInt(swYear), swMonth, Integer.parseInt(swDay));
        if(routeId.equals("") || busType.equals("") || status.equals("") || licensePlate.equals("") || swDay.equals("") || swMonth ==0 || swYear.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin");
        }
        else{
            ResultSet rs;
            Connection con = AccountManagement.establishCon();
            Statement st = null;
            try{
                String sql = "INSERT BUS"
                        + " OUTPUT INSERTED.bus_id"
                        + " VALUES(" +routeId+", '"+ licensePlate+"', N'"+ busType+"', '"+swDate+"', "+ Integer.parseInt(status)+")";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                rs.next();
                int id = rs.getInt("bus_id");
                
                Object[] row = new Object[6];
                row[0] = id;
                row[1] = routeId;
                row[2] = licensePlate;
                row[3] = busType;
                row[4] = swDate;
                row[5] = Integer.parseInt(status);
                
                DefaultTableModel model = (DefaultTableModel)busTable.getModel();
                model.addRow(row);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                // done addButton tomorrow do delete and update and link frame
                    busTable.clearSelection();
                routeIdText.setText("");
                busTypeCombo.setSelectedItem("--Chọn loại xe--");
                statusCombo.setSelectedItem("Hoạt động");
                licensePlateText.setText("");
                swDayText.setText("");
                swMonthCombo.setSelectedItem("Chọn tháng");
                swYearText.setText("");
                deleteButton.setEnabled(false);
                updateButton.setEnabled(false);
             }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        

    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = busTable.getSelectedRow();
        String cell = busTable.getModel().getValueAt(row, 0).toString();
        String deleteQuery = "DELETE FROM BUS WHERE bus_id= "+cell;
        Connection con = establishCon();
        Statement st =null;
        try{
            st = con.createStatement();
            st.executeUpdate(deleteQuery);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            DefaultTableModel dm = (DefaultTableModel)busTable.getModel();
            dm.removeRow(row);
            routeIdText.setText("");
        busTypeCombo.setSelectedItem("--Chọn loại xe--");
        statusCombo.setSelectedItem("Hoạt động");
        licensePlateText.setText("");
        swDayText.setText("");
        swMonthCombo.setSelectedItem("Chọn tháng");
        swYearText.setText("");
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
         
        }
        catch(Exception e){
            e.printStackTrace();
            return;
        }
        finally{
            if(con!=null)
            {
                try{
                    con.close();
                }
                catch (Exception e){
                    e.printStackTrace();
                }
            }
            if(st != null)
            {
                try
                {
                    st.close();
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = busTable.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel) busTable.getModel();
        if(selectedRow >=0)
        {
            String routeId, licensePlate, busType;
            int day, swMonth, year;
            int status;
            LocalDate swDate;
            
            routeId = routeIdText.getText();
            licensePlate = licensePlateText.getText();
            busType = busTypeCombo.getSelectedItem().toString();
            if(statusCombo.getSelectedItem().toString().equals("Hoạt động"))
            {
                status = 1;
            }
            else if(statusCombo.getSelectedItem().toString().equals("Không hoạt động"))
                    {
                        status = 0;
                    }
            else{
                status = 5;
            }
            day = Integer.parseInt(swDayText.getText());
            switch (swMonthCombo.getSelectedItem().toString())
       {
            case "Tháng 1":
                swMonth = 1;
                break;
            case "Tháng 2":
                swMonth = 2;
                break;
            case "Tháng 3":
                swMonth = 3;
                break;
            case "Tháng 4":
                swMonth = 4;
                break;
            case "Tháng 5":
                swMonth = 5;
                break;
            case "Tháng 6":
                swMonth = 6;
                break;
            case "Tháng 7":
                swMonth = 7;
                break;
            case "Tháng 8":
                swMonth = 8;
                break;
            case "Tháng 9":
                swMonth = 9;
                break;
            case "Tháng 10":
                swMonth = 10;
                break;
            case "Tháng 11":
                swMonth = 11;
                break;
            case "Tháng 12":
                swMonth = 12;
                break;
            default: 
                swMonth = 0;
                       
        }
            
            year = Integer.parseInt(swYearText.getText());
            swDate = LocalDate.of(year, swMonth, day);
            
            model.setValueAt(routeId, selectedRow, 1);
            model.setValueAt(licensePlate, selectedRow, 2);
            model.setValueAt(swDate, selectedRow, 4);
            model.setValueAt(busType, selectedRow, 3);
            model.setValueAt(status, selectedRow, 5);
            
            Connection con = establishCon();
            Statement st;
            String busId = busTable.getModel().getValueAt(selectedRow, 0).toString();
             try{
                String updateSql = "UPDATE BUS "+
                        "SET route_id= '" +routeId+"', license_plate= '"+licensePlate+"', bus_type= N'"+busType +"', start_use = '"+swDate+"', status='" +status
                        + "' WHERE bus_id =" +busId; 
                st = con.createStatement();
                st.executeUpdate(updateSql);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                routeIdText.setText("");
        busTypeCombo.setSelectedItem("--Chọn loại xe--");
        statusCombo.setSelectedItem("Hoạt động");
        licensePlateText.setText("");
        swDayText.setText("");
        swMonthCombo.setSelectedItem("Chọn tháng");
        swYearText.setText("");
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
                
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        busTable.clearSelection();
        routeIdText.setText("");
        busTypeCombo.setSelectedItem("--Chọn loại xe--");
        statusCombo.setSelectedItem("Hoạt động");
        licensePlateText.setText("");
        swDayText.setText("");
        swMonthCombo.setSelectedItem("Chọn tháng");
        swYearText.setText("");
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void busTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTableMouseClicked
        // TODO add your handling code here:
         int selectedRow = busTable.getSelectedRow();
         
        DefaultTableModel dfModel = (DefaultTableModel) busTable.getModel();
        routeIdText.setText(dfModel.getValueAt(selectedRow, 1).toString());
        licensePlateText.setText(dfModel.getValueAt(selectedRow, 2).toString());
        busTypeCombo.setSelectedItem(dfModel.getValueAt(selectedRow, 3).toString());
        
        String swDate = dfModel.getValueAt(selectedRow, 4).toString();
        String swDateDecompose[] = swDate.split("-");
        
        swDayText.setText(swDateDecompose[2]);
        swYearText.setText(swDateDecompose[0]);
        
        deleteButton.setEnabled(true);
        updateButton.setEnabled(true);
        
        switch (swDateDecompose[1])
        {
            case "01":
                swDateDecompose[1] = "Tháng 1";
                break;
            case "02":
                swDateDecompose[1] = "Tháng 2";
                break;
            case "03":
                swDateDecompose[1] = "Tháng 3";
                break;
            case "04":
                swDateDecompose[1] = "Tháng 4";
                break;
            case "05":
                swDateDecompose[1] = "Tháng 5";
                break;
            case "06":
                swDateDecompose[1] = "Tháng 6";
                break;
            case "07":
                swDateDecompose[1] = "Tháng 7";
                break;
             case "08":
                swDateDecompose[1] = "Tháng 8";
                break;
            case "09":
                swDateDecompose[1] = "Tháng 9";
                break;
            case "10":
                swDateDecompose[1] = "Tháng 10";
                break;
            case "11":
                swDateDecompose[1] = "Tháng 11";
                break;
            case "12":
                swDateDecompose[1] = "Tháng 12";
                break;
            default: 
                swDateDecompose[1] = "Chọn tháng";
                       
        }
        swMonthCombo.setSelectedItem(swDateDecompose[1]);
        
        statusCombo.setSelectedItem(dfModel.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_busTableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   Login log = new Login();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
                //System.out.println(this.infor);
               
              // System.out.println(bus.infor);
               this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
           QLVe tick = new QLVe();
                tick.setVisible(true);
                tick.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               tick.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         QLTime time = new QLTime();
                time.setVisible(true);
                time.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               time.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        QLChuyen route = new QLChuyen();
                route.setVisible(true);
                route.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               route.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
          PhanCong work = new PhanCong();
                work.setVisible(true);
                work.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               work.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        Thongke st = new Thongke();
                st.setVisible(true);
                st.setLocationRelativeTo(null);
               // System.out.println(this.infor);
               st.setInfor(this.infor);
               this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusManagement().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTable busTable;
    private javax.swing.JComboBox<String> busTypeCombo;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton empmButton;
    private javax.swing.JPanel inforPanel;
    private javax.swing.JTextPane inforText;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField licensePlateText;
    private javax.swing.JTextField routeIdText;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTextField swDayText;
    private javax.swing.JComboBox<String> swMonthCombo;
    private javax.swing.JTextField swYearText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
